# Generated by Django 4.0.5 on 2022-06-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('confirm', 'подтверждённый'), ('new', 'новый'), ('canceled', 'отменённый')], default='new', max_length=254),
        ),
    ]
